server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/auth_db
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

jwt:
  secret: my_secret_key
  expiration: 3600000 # 1 giờ (ms)
