services:
  # Database
  mariadb:
    image: mariadb:latest
    container_name: bookstore-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - bookstore-network

  # Eureka Service
  eureka-service:
    build: ./eureka_service
    container_name: bookstore-eureka-service
    ports:
      - "8762:8762"
    networks:
      - bookstore-network
    restart: on-failure
    healthcheck:
      test: curl -f http://localhost:8762/actuator/health || exit 0
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 30s

  # Api Gateway
  api-gateway:
    build: ./api-gateway
    container_name: bookstore-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
    networks:
      - bookstore-network
    restart: on-failure
    healthcheck:
      test: curl -f http://localhost:8080/actuator/health || exit 0
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 30s

  # Auth Service
  auth-service:
    build: ./auth-service
    container_name: bookstore-auth-service
    ports:
      - "8002:8002"
    depends_on:
      - mariadb
      - eureka-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/auth-service-bookstore?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka-service:8762/eureka/
    networks:
      - bookstore-network
    restart: on-failure
    healthcheck:
      test: curl -f http://localhost:8002/actuator/health || exit 0
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 30s

  # User Service
  user-service:
    build: ./user_service
    container_name: bookstore-user-service
    ports:
      - "8001:8001"
    depends_on:
      - mariadb
      - eureka-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/user-service-bookstore?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka-service:8762/eureka/
    networks:
      - bookstore-network
    restart: on-failure
    healthcheck:
      test: curl -f http://localhost:8001/actuator/health || exit 0
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 30s

  # Book Service
  book-service:
    build: ./book-service
    container_name: bookstore-book-service
    ports:
      - "8003:8003"
    depends_on:
      - mariadb
      - eureka-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/book-service-bookstore?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka-service:8762/eureka/
    networks:
      - bookstore-network
    restart: on-failure
    healthcheck:
      test: curl -f http://localhost:8003/actuator/health || exit 0
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 30s

  # Cart Service
  cart-service:
    build: ./cart-service
    container_name: bookstore-cart-service
    ports:
      - "8004:8004"
    depends_on:
      - mariadb
      - eureka-service
      - book-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/cart-service-bookstore?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka-service:8762/eureka/
      - BOOK_SERVICE_URL=http://book-service:8003
    networks:
      - bookstore-network
    restart: on-failure
    healthcheck:
      test: curl -f http://localhost:8004/actuator/health || exit 0
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 30s

  # Order Service
  order-service:
    build: ./order-service
    container_name: bookstore-order-service
    ports:
      - "8005:8005"
    depends_on:
      - mariadb
      - eureka-service
      - cart-service
      - user-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/order-service-bookstore?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka-service:8762/eureka/
      - PAYMENT_SERVICE_URL=http://payment-service:8989
      - CART_SERVICE_URL=http://cart-service:8004
      - USER_SERVICE_URL=http://user-service:8001
    networks:
      - bookstore-network
    restart: on-failure
    healthcheck:
      test: curl -f http://localhost:8005/actuator/health || exit 0
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 30s

  # Payment Service (Node.js)
  payment-service:
    build: ./payment-service
    container_name: bookstore-payment-service
    ports:
      - "8989:8989"
    depends_on:
      - mariadb
      - eureka-service
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASS=root
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka-service:8762/eureka/
      - ORDER_SERVICE_URL=http://order-service:8005
      - CART_SERVICE_URL=http://cart-service:8004
    networks:
      - bookstore-network
    restart: on-failure
    healthcheck:
      test: curl -f http://localhost:8989/health || exit 0
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 30s

  # Chatbox Service
  chatbox-service:
    build: ./chatbox-service
    container_name: bookstore-chatbox-service
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASS=root
    networks:
      - bookstore-network
    restart: on-failure
    healthcheck:
      test: curl -f http://localhost:3000/health || exit 0
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 30s

networks:
  bookstore-network:
    driver: bridge

volumes:
  mariadb-data:
